language: python
python:
  - "3.9"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

services:
  - postgresql

before_install:
  - current_stable=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
  - wget https://chromedriver.storage.googleapis.com/$current_stable/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/bin/chromedriver
  - python --version
  - pip install -U pip
  - pip install codecov
  - psql -c 'create database pur_beurre;' -U postgres

install:
  - pip install -r requirements.txt

before_script:
  - cd purbeurre
  - cp purbeurre/.env.example purbeurre/.env

script:
  - python manage.py collectstatic --noinput
  - python manage.py test -b
  - coverage xml

after_success:
  - codecov