# Generated by Django 3.2.5 on 2021-09-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubstitute',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='usersubstitute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubstitute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
