# Generated by Django 3.2.5 on 2022-04-15 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('substitute', '0002_auto_20210924_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubstitute',
            name='original_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitued_set', to='product.product'),
        ),
        migrations.AlterField(
            model_name='usersubstitute',
            name='substitute_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituting_set', to='product.product'),
        ),
    ]
